version: '3.8'

services:
  db:
    image: postgres:15
    container_name: photo_db
    restart: always
    environment:
      - POSTGRES_USER=NobleFour
      - POSTGRES_PASSWORD=SkullCarver
      - POSTGRES_DB=photo_drive
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: photo_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db_data:

